build:
  maxIssues: 0
  excludeCorrectable: false
config:
  validation: true
processors:
  active: true
style:
  MagicNumber:
    active: false
  MaxLineLength:
    active: true
    maxLineLength: 140
  WildcardImport:
    active: false
