name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: ktlint
        run: ./gradlew ktlintCheck
      - name: detekt
        run: ./gradlew detekt
      - name: Unit tests
        run: ./gradlew test
      - name: Android lint
        run: ./gradlew :androidApp:lint
      - name: Assemble release
        run: ./gradlew :androidApp:assembleRelease
      - name: Upload release APK
        uses: actions/upload-artifact@v4
        with:
          name: android-release
          path: androidApp/build/outputs/apk/release/*.apk
